### ISSUE TITLE
Remove Thickness3D_LIBRARIES

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKThickness3D#1]
Since the module does not create a library containing compiled `.cxx` files (i.e. there is no `src/` folder), this line should be removed:

https://github.com/T4mmi/ITKThickness3D/blob/1f638feff017e95fa86e1f53b7077dbd0c006eac/CMakeLists.txt#L4

**Comment by T4mmi** [comment]
Ok, I removed it
