### ISSUE TITLE
Data/medial_thickness.tif is missing

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKThickness3D#2]
The *test/Data/medial_thickness.tif* file is missing, referenced here:

https://github.com/T4mmi/ITKThickness3D/blob/1f638feff017e95fa86e1f53b7077dbd0c006eac/test/CMakeLists.txt#L15 

and creating the error on CircleCI:

```
CMake Warning (dev) at /usr/share/cmake-3.11/Modules/ExternalData.cmake:690 (message):
  Data file referenced by argument

    DATA{Data/medial_thickness.tif}

  corresponds to source tree path

    test/Data/medial_thickness.tif

  that does not exist as a file (with or without an extension)!
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/ExternalData.cmake:494 (_ExternalData_arg)
  /usr/share/cmake-3.11/Modules/ExternalData.cmake:333 (ExternalData_expand_arguments)
  /ITK/CMake/ITKModuleTest.cmake:127 (ExternalData_add_test)
  test/CMakeLists.txt:12 (itk_add_test)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by T4mmi** [comment]
Yes indeed, `medial_thickness.tif` is the output image "produced" by the filter, it is created by the test.
But I might be wrong with how to do it (maybe I should add a 'blank' image and the test should modify it?)

**Comment by thewtex** [comment]
Ah, in that case, we want to write the output to the build directory, typically at `${ITK_TEST_OUTPUT_DIR}`, then compare the output to a baseline image. This is specified by passing arguments to the `--compare` flag of the ITK test driver. These come before the name of the test. Here is an example:

https://github.com/InsightSoftwareConsortium/ITKAnisotropicDiffusionLBR/blob/087c5fda829a1b08f4ce6d1a7cebdb9af23d1080/test/CMakeLists.txt#L14-L15

**Comment by T4mmi** [comment]
Ok, thanks I didn't know !
regarding the `${ITK_TEST_OUTPUT_DIR}`, is it created 'on the fly' along the input data ?

based on the [doc](https://itk.org/Wiki/ITK/Procedure_for_Adding_a_Test_(itk_3.x)) I don't find the actual path of `${ITK_DATA_ROOT}` nor `${ITK_TEST_OUTPUT_DIR}`.

also, it seems the `--compare` require a "comparison method" (which might be tricky in this particular case), am I wrong ?

**Comment by thewtex** [comment]
Good questions.

`ITK_TEST_OUTPUT_DIR` is defined by the ITK module macros and can be assumed to be defined.

Avoid `ITK_DATA_ROOT` and put all required data in the module's `test/Input` and `test/Baseline` folders.

There are a number of [additional options](https://github.com/InsightSoftwareConsortium/ITK/blob/1f468a1ebfc8dad23c652b977d96d7f6bba7717e/Modules/Core/TestKernel/src/itkTestDriverInclude.cxx#L71-L147) that can be used with `--compare` to specify tolerances, which can make comparisons more robust.
