### ISSUE TITLE
Input 3D image format support

### ISSUE THREAD

**Issue by meghalD** [InsightSoftwareConsortium/ITKThickness3D#28]
I tried to read .obj file both as mesh and voxels. but the code image = itk.imread(input) is unable to read the file. 
It throws an error :
reader = TemplateReaderType.New(**kwargs)
  File "/home/anaconda3/envs/Pose/lib/python3.6/site-packages/itkTemplate.py", line 471, in New
    return self._NewImageReader(itk.ImageFileReader, False, 'FileName', *args, **kwargs)
  File "/home/anaconda3/envs/Pose/lib/python3.6/site-packages/itkTemplate.py", line 538, in _NewImageReader
    raise RuntimeError("Could not create IO object for reading file %s" % inputFileName + msg)
RuntimeError: Could not create IO object for reading file 01.obj

what exactly should be the input and output so as to convert mesh or voxel 3D object to skeleton.

**Comment by T4mmi** [comment]
Hi @meghalD ,
thanks for using our tool !

it seems that the error is related to the [ITK](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html) image reader and not to our plugin.
Since i'm not used to *.obj* I might not be a great help here ...

**Comment by meghalD** [comment]
what is the format normally taken as input in 3D image ?Please specify so that I can find a work around to feed that as an input.

**Comment by T4mmi** [comment]
There is no "default" format for images.

**ITKTickness3D** will work with any *ITK 3D image object* as defined by ITK. If you wanna read an image file (i.e. load a file inside ITK), then you should look at the ITK ImageIO doc:
- [ImageFileReader](https://itk.org/Doxygen/html/classitk_1_1ImageFileReader.html)
- [Read an Image](https://itk.org/ITKExamples/src/IO/ImageBase/ReadAnImage/Documentation.html)
- [Read an unknown image format](https://itk.org/ITKExamples/src/IO/ImageBase/ReadUnknownImageType/Documentation.html)

All I know is that natively is works with 3D TIFF (bigtiff supported) and with DICOM series (using dicom series reader)...

**Comment by meghalD** [comment]
This has to be done seperately in C++? Can I use this functions in python ?

**Comment by T4mmi** [comment]
Nope, no need for C++.  
You can use *almost all* these functions through the [Python wrappings](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html)
