### ISSUE TITLE
Restrict wrapping to 3D

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKThickness3D#3]
The `itk::MedialThicknessImageFilter` is dependent on the `itk::BinaryThinningImageFilter3D`, which is only defined for 3D images. ITK compile time concept checks may stop compilation for 2D images, since it would not be valid.

In the Python wrapping add a third parameter, `3` to restrict wrapping for that dimension, i.e.

```
  itk_wrap_image_filter("${WRAP_ITK_SCALAR}" 2 3)
```

More details can be found in the [wrapping macro documentation](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html#x55-1560009.5).

**Comment by T4mmi** [comment]
wow, indeed that makes sense. I totaly missed that line !
thanks a lot, I'll try to make it compile ;)

**Comment by T4mmi** [comment]
Hi again, I've been running some tests and it seems that most of my troubles comes from the templates management...

How to "force" (more like control) the `TInputImage` and `TInputImage` with an `ImageToImageFilter` ?
```
template <class TInputImage, class TOutputImage>
public ImageToImageFilter<TInputImage, TOutputImage>
```
And what about the ensuing python wrapping ? 

> _Should we write the C-code without restrictions and 'control' ImageTypes with the wrapping macro ?_
when I try:
```
  UNIQUE(wrap_image_types "${WRAP_ITK_SCALAR};UC")
  foreach(type ${wrap_image_types})
    itk_wrap_image_filter_combinations("${type}" "UC" 3)
  endforeach()
```
I end up with errors such as `ITKs/Modules/Core/Common/include/itkConceptChecking.h:571:32: error: no viable conversion from 'UniqueType<unsigned char>' to 'UniqueType<short>'`?

**Comment by thewtex** [comment]
It depends on the specific issue...

Is there more of the backtrace for the error `ITKs/Modules/Core/Common/include/itkConceptChecking.h:571:32: error: no viable conversion from 'UniqueType<unsigned char>' to 'UniqueType<short>'`. That is, which instantiation is causing this issue?

The wrapping macros allow wrapping an `ImageToImageFilter` with the same pixel type and dimension (a common use case). `itk_wrap_image_filter_combinations` allows wrapping with different types of input and output images. The `itk_wrap_template` macro allows wrapping any class (not just an `ImageToImageFilter`) with specification of all types.

**Comment by T4mmi** [comment]
Thanks I managed to do it for the wrapping !  
Indeed the errors did not seem related to wrapping... *got a bit confused as backtrace are not always so descriptive*
