### ISSUE TITLE
Build with older ITK version

### ISSUE THREAD

**Issue by nnzzll** [InsightSoftwareConsortium/ITKThickness3D#43]
I want to build this module in ITK-5.1.2.
I followed the instruction to clone the respoitory under Modules/External，
however, when I configure the source code there is no option "Module_Thickness3D" and after building I can't find the module in ITK-build directory either.
Did I miss any detail?

**Comment by thewtex** [comment]
Hi,

Cloning into `Modules/External` is not necessary. Just enable the `Module_Thinckness3D` CMake option in `ITK`'s build. Please re-open if you still have questions. Thanks!
