### ISSUE TITLE
Medial thickness values

### ISSUE THREAD

**Issue by Aleksandra-Atanova** [InsightSoftwareConsortium/ITKThickness3D#46]
Hi! As I understood, MedialThicknessImageFilter3D counts diameter of the local maximal fitting sphere, but returns only the skeleton, based on these calculations. Is there a possibility to get these values of diameters for further analysis of thickness?

**Comment by phcerdan** [comment]
Hi! You can get the value of the radius of the sphere from the distance map image.

**Comment by Aleksandra-Atanova** [comment]
Ok, thank you!
